import type { Metadata } from "next";
import "../styles/globals.css"

import Topbar from "@/components/topbar";
import { Contex } from "@/components/Contex";


export const metadata: Metadata = {
  title: "admin dashboard",
  description: "Generated by behnam adabzadeh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <Contex>
        <body>
          <Topbar />
          {children}
        </body>
      </Contex>
    </html>
  );
}
