import type { Metadata } from "next";
import "../styles/globals.css"


export const metadata: Metadata = {
  title: "admin dashboard",
  description: "Generated by behnam adabzadeh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body>
        {children}
      </body>
    </html>
  );
}
