import type { Metadata } from "next";
import localFont from 'next/font/local'
import "../styles/globals.css"

import Topbar from "@/components/topbar";
import { Contex } from "@/components/Contex";



export const metadata: Metadata = {
  title: "admin dashboard",
  description: "Generated by behnam adabzadeh",
};

const IranSans = localFont({
  src : "../public/fonts/IRANSansWeb.woff2"
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={IranSans.className}>
      <Contex>
        <body>
          <Topbar />
          {children}
        </body>
      </Contex>
    </html>
  );
}
