import type { Metadata } from "next";
import Topbar from "../../components/topbar";
import Sidebar from "../../components/sidebar";


export const metadata: Metadata = {
  title: "admin dashboard",
  description: "Generated by behnam adabzadeh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="mx-5 md:mx-10 lg:mx-20 mt-5 grid md:grid-cols-4 sm:grid-cols-3 sm:gap-3">
      <div className="hidden sm:flex sm:col-span-1">
        <Sidebar />
      </div>
      <div className="sm:col-span-2 md:col-span-3">
        {children}
      </div>
    </div>
  );
}
