import type { Metadata } from "next";
import Topbar from "../../components/topbar";
import Sidebar from "../../components/sidebar";


export const metadata: Metadata = {
  title: "admin dashboard",
  description: "Generated by behnam adabzadeh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="mx-20">
      {children}
    </div>
  );
}
