import type { Metadata } from "next";
import Topbar from "../../components/topbar";
import Sidebar from "../../components/sidebar";


export const metadata: Metadata = {
  title: "admin dashboard",
  description: "Generated by behnam adabzadeh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body >
        <Topbar/>
        {children}
      </body>
    </html>
  );
}
